## MoveIt uses this configuration for controller management

#moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

#moveit_simple_controller_manager:
#  controller_names:
#    - arm_controller
#    - gripper_controller
#    #- whole_body_controller
#
#  arm_controller:
#    type: FollowJointTrajectory
#    joints:
#      - joint1
#      - joint2
#      - joint3
#      - joint4
#  gripper_controller:
#    type: FollowJointTrajectory
#    joints:
#      - gripper_left_joint
#  #whole_body_controller:
#  #  type: FollowJointTrajectory
#  #  joints:
#  #    - virtual_joint
#  #    - joint1
#  #    - joint2
#  #    - joint3
#  #    - joint4


moveit_simple_controller_manager:
  ros__parameters:
    controller_names:
      - arm_controller
      - gripper_controller

    arm_controller:
      type: FollowJointTrajectory
      action_ns: follow_joint_trajectory
      default: true
      joints:
        - joint1
        - joint2
        - joint3
        - joint4

    gripper_controller:
      type: FollowJointTrajectory
      action_ns: follow_joint_trajectory
      default: false
      joints:
        - gripper_left_joint

moveit_controller_manager:
  ros__parameters:
    type: moveit_simple_controller_manager/MoveItSimpleControllerManager
