controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


arm_controller:
   ros__parameters:
      type: joint_trajectory_controller/JointTrajectoryController
      joints: ["joint1", "joint2", "joint3", "joint4"]
      command_interfaces: ["position"]
      state_interfaces: ["position", "velocity"]

gripper_controller:
  ros__parameters:
    joints: ["gripper_left_joint", "gripper_right_joint"]
    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"]
